# Generated by Django 2.2.2 on 2019-07-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palabra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('versiculo', models.TextField()),
                ('autor', models.CharField(max_length=20)),
                ('fecha_publicado', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
